version: "3.5"

services:
  wordpress:
    image: wordpress
    environment:
      HOST: http://0.0.0.0
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./html:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./sql/initdb:/docker-entrypoint-initdb.d:ro
      - ./data:/var/lib/mysql
